### ISSUE TITLE
USER STORY: Sign-In Page

### ISSUE THREAD

**Issue by intisarosman1** [SeattleColleges/belindas-closet-nextjs#132]
As a developer, I would like to have a functional sign-in page modified to fit the web app's (NSC Belinda's Closet) theme.

- [x] [Add frog mascot above sign-in box](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/155)
- [x] [Remove placeholder "arrow pointing into box" image](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/155)
- [x] [Modify text color to be visible when text box is filled](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/170)
- [x] [Implement ability to log in](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/172)
