### ISSUE TITLE
USER STORY: Navigation Bar

### ISSUE THREAD

**Issue by heosman** [SeattleColleges/belindas-closet-nextjs#142]
As a student, I will want to be able to navigate the website to find clothes from different categories.

Tasks
- [x] [Add a “products” dropdown menu for product categories](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/183)
- [x] [Have the categories listed in the dropdown with no action on click](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/183)
- [x] [Remove “sign up” link from nav bar](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/145)
- [x] [Add donation info page link to nav bar](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/145)
