### ISSUE TITLE
USER STORY: Individual Product Page

### ISSUE THREAD

**Issue by intisarosman1** [SeattleColleges/belindas-closet-nextjs#255]
As a developer, I'd like to make these changes to the individual product page:

- [x] [Add functionality to delete and archive buttons (frontend to backend integration)](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/256)
- [x] [Add functionality to edit button](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/265)
- [x] [Buttons only visible to creator and admins](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/265)
