### ISSUE TITLE
USER STORY: Archived Events Page

### ISSUE THREAD

**Issue by intisarosman1** [SeattleColleges/belindas-closet-nextjs#324]
As a developer, I will want to create a placeholder Archived Events page.

- [ ] [Create placeholder Archived Events page](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/325)
- [ ] [Create View Archived Events button on admin page](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/326)
- [ ] [Create View Archived Events button on creator page](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/326)
